/* THIS FILE IS UNSUPPORTED
TO USE FORS DEVELOPMENT AND TESTING PURPOSES */

import { Tank } from './Tank';

// export const TANKS: Tank[] = [
//   {
//     id: 'TM23401',

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23402",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23403",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23417",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23405",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23406",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23407",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23408",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },

//   {
//     id: "TM23409",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23410",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23411",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23414",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23415",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "TM23416",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "15",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "16",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "17",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "18",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "19",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "20",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21401",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21402",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21403",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21404",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21405",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21406A",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21406B",

//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21407",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },

//   {
//     id: "2114",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "2115",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21413",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21414",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21415",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21416",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "215",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "216",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21420",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21421",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21422",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21423",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21424",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21425",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21426",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21427",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21428",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21429",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21430",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21431",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21432",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21433",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21434",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   },
//   {
//     id: "21435",
//     matDescription: 'Agua',
//     batchNo: '1',
//     client: 'Tesla',
//     startDate: '04-03-2021',
//     deliveryDate: '07-03-2021',
//     etapaActual: 'Cargando',
//     status: 'green',
//   }
// ];
